services:
  - type: web
    name: car-for-u
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AUTODEV_API_KEY
        sync: false
      - key: PLANNER_API_KEY
        sync: false
